# This code 
env: TEXDIR=/usr/local/texlive/2013
env: PATH=$TEXDIR/bin/x86_64-linux:$PATH
env: CTAN_MIRROR_URL='http://mirror.aarnet.edu.au/pub/CTAN'

before_script:
  - sudo ./latex_env_setup.sh
  - wget ${CTAN_MIRROR_URL}/systems/texlive/tlnet/install-tl-unx.tar.gz
  - tar xzf install-tl-unx.tar.gz
  - ./install-tl-*/install-tl -no-gui -profile texlive.profile
  - tlmgr install mdframed preprint enumitem etoolbox titlesec xmpincl comment latexmk lm memoir listings xcolor url l3packages l3kernel placeins microtype float latex-bin fancyhdr graphics psnfss pdftex-def oberdiek colortbl hyperref

script: "make"

