env:
  global:
    - PATH: /usr/local/texlive/2013/bin/x86_64-linux:$PATH
    - GH_REF: github.com/BioplatformsAustralia/handout-template.git
    - secure: "J/oFevIbuIyl1P16qdSVaNeJ0P1rL5Hub92SlDcNmhZ6NGu7+9N43fDs+uf3ihCmu664wZDKzB8YACetOfZ+XrZ9M72IfI3CzA7OWrx8elsub+WvaaOeVp3D+tDgNzxhXVRVJl5jZMmgEh5KjZ6GNshuTEPrIN+14s8bR4CciEM="
before_script:
  - cd ./developers/ && sudo -E ./texlive_install.sh && cd ../
script: "make && bash ./developers/deploy-ghpages.sh"
